### ISSUE TITLE
Commands needed

### ISSUE THREAD

**Issue by brennan-macaig** [FRC-1721/TetrisToaster-Platform#1]
Commands need to be written to control the Grabber subsystem - the only complete subsystem at this point.

If issue is not assigned in git by COB Saturday, 5/5/18, then this issue will be marked closed and a push will be made.

**Comment by KenwoodFox** [comment]
What?

**Comment by brennan-macaig** [comment]
Issue will be marked as closed/solved.

The idea behind this repo is to clean-up and generally re-write some of the code in a neater fashion.

Hence, new commands for the "grabber"
